/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as FrontRouteImport } from './pages/front/route'
import { Route as AuthRegisterImport } from './pages/auth/register'
import { Route as AuthLoginImport } from './pages/auth/login'
import { Route as AuthForgetImport } from './pages/auth/forget'
import { Route as FrontVideoIndexImport } from './pages/front/video/index'
import { Route as FrontTopicIndexImport } from './pages/front/topic/index'
import { Route as FrontSubscribeIndexImport } from './pages/front/subscribe/index'
import { Route as FrontSignIndexImport } from './pages/front/sign/index'
import { Route as FrontLessonIndexImport } from './pages/front/lesson/index'
import { Route as FrontVideoShowImport } from './pages/front/video/show'
import { Route as FrontTopicShowImport } from './pages/front/topic/show'
import { Route as FrontLessonShowImport } from './pages/front/lesson/show'
import { Route as FrontChapterSystemImport } from './pages/front/chapter/system'
import { Route as FrontChapterShowImport } from './pages/front/chapter/show'
import { Route as FrontChapterProjectImport } from './pages/front/chapter/project'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/about.lazy').then((d) => d.Route))

const FrontRouteRoute = FrontRouteImport.update({
  id: '/front',
  path: '/front',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/index.lazy').then((d) => d.Route))

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgetRoute = AuthForgetImport.update({
  id: '/auth/forget',
  path: '/auth/forget',
  getParentRoute: () => rootRoute,
} as any)

const FrontVideoIndexRoute = FrontVideoIndexImport.update({
  id: '/video/',
  path: '/video/',
  getParentRoute: () => FrontRouteRoute,
} as any)

const FrontTopicIndexRoute = FrontTopicIndexImport.update({
  id: '/topic/',
  path: '/topic/',
  getParentRoute: () => FrontRouteRoute,
} as any)

const FrontSubscribeIndexRoute = FrontSubscribeIndexImport.update({
  id: '/subscribe/',
  path: '/subscribe/',
  getParentRoute: () => FrontRouteRoute,
} as any)

const FrontSignIndexRoute = FrontSignIndexImport.update({
  id: '/sign/',
  path: '/sign/',
  getParentRoute: () => FrontRouteRoute,
} as any)

const FrontLessonIndexRoute = FrontLessonIndexImport.update({
  id: '/lesson/',
  path: '/lesson/',
  getParentRoute: () => FrontRouteRoute,
} as any)

const FrontVideoShowRoute = FrontVideoShowImport.update({
  id: '/video/show',
  path: '/video/show',
  getParentRoute: () => FrontRouteRoute,
} as any)

const FrontTopicShowRoute = FrontTopicShowImport.update({
  id: '/topic/show',
  path: '/topic/show',
  getParentRoute: () => FrontRouteRoute,
} as any)

const FrontLessonShowRoute = FrontLessonShowImport.update({
  id: '/lesson/show',
  path: '/lesson/show',
  getParentRoute: () => FrontRouteRoute,
} as any)

const FrontChapterSystemRoute = FrontChapterSystemImport.update({
  id: '/chapter/system',
  path: '/chapter/system',
  getParentRoute: () => FrontRouteRoute,
} as any)

const FrontChapterShowRoute = FrontChapterShowImport.update({
  id: '/chapter/show',
  path: '/chapter/show',
  getParentRoute: () => FrontRouteRoute,
} as any)

const FrontChapterProjectRoute = FrontChapterProjectImport.update({
  id: '/chapter/project',
  path: '/chapter/project',
  getParentRoute: () => FrontRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/front': {
      id: '/front'
      path: '/front'
      fullPath: '/front'
      preLoaderRoute: typeof FrontRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/forget': {
      id: '/auth/forget'
      path: '/auth/forget'
      fullPath: '/auth/forget'
      preLoaderRoute: typeof AuthForgetImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/front/chapter/project': {
      id: '/front/chapter/project'
      path: '/chapter/project'
      fullPath: '/front/chapter/project'
      preLoaderRoute: typeof FrontChapterProjectImport
      parentRoute: typeof FrontRouteImport
    }
    '/front/chapter/show': {
      id: '/front/chapter/show'
      path: '/chapter/show'
      fullPath: '/front/chapter/show'
      preLoaderRoute: typeof FrontChapterShowImport
      parentRoute: typeof FrontRouteImport
    }
    '/front/chapter/system': {
      id: '/front/chapter/system'
      path: '/chapter/system'
      fullPath: '/front/chapter/system'
      preLoaderRoute: typeof FrontChapterSystemImport
      parentRoute: typeof FrontRouteImport
    }
    '/front/lesson/show': {
      id: '/front/lesson/show'
      path: '/lesson/show'
      fullPath: '/front/lesson/show'
      preLoaderRoute: typeof FrontLessonShowImport
      parentRoute: typeof FrontRouteImport
    }
    '/front/topic/show': {
      id: '/front/topic/show'
      path: '/topic/show'
      fullPath: '/front/topic/show'
      preLoaderRoute: typeof FrontTopicShowImport
      parentRoute: typeof FrontRouteImport
    }
    '/front/video/show': {
      id: '/front/video/show'
      path: '/video/show'
      fullPath: '/front/video/show'
      preLoaderRoute: typeof FrontVideoShowImport
      parentRoute: typeof FrontRouteImport
    }
    '/front/lesson/': {
      id: '/front/lesson/'
      path: '/lesson'
      fullPath: '/front/lesson'
      preLoaderRoute: typeof FrontLessonIndexImport
      parentRoute: typeof FrontRouteImport
    }
    '/front/sign/': {
      id: '/front/sign/'
      path: '/sign'
      fullPath: '/front/sign'
      preLoaderRoute: typeof FrontSignIndexImport
      parentRoute: typeof FrontRouteImport
    }
    '/front/subscribe/': {
      id: '/front/subscribe/'
      path: '/subscribe'
      fullPath: '/front/subscribe'
      preLoaderRoute: typeof FrontSubscribeIndexImport
      parentRoute: typeof FrontRouteImport
    }
    '/front/topic/': {
      id: '/front/topic/'
      path: '/topic'
      fullPath: '/front/topic'
      preLoaderRoute: typeof FrontTopicIndexImport
      parentRoute: typeof FrontRouteImport
    }
    '/front/video/': {
      id: '/front/video/'
      path: '/video'
      fullPath: '/front/video'
      preLoaderRoute: typeof FrontVideoIndexImport
      parentRoute: typeof FrontRouteImport
    }
  }
}

// Create and export the route tree

interface FrontRouteRouteChildren {
  FrontChapterProjectRoute: typeof FrontChapterProjectRoute
  FrontChapterShowRoute: typeof FrontChapterShowRoute
  FrontChapterSystemRoute: typeof FrontChapterSystemRoute
  FrontLessonShowRoute: typeof FrontLessonShowRoute
  FrontTopicShowRoute: typeof FrontTopicShowRoute
  FrontVideoShowRoute: typeof FrontVideoShowRoute
  FrontLessonIndexRoute: typeof FrontLessonIndexRoute
  FrontSignIndexRoute: typeof FrontSignIndexRoute
  FrontSubscribeIndexRoute: typeof FrontSubscribeIndexRoute
  FrontTopicIndexRoute: typeof FrontTopicIndexRoute
  FrontVideoIndexRoute: typeof FrontVideoIndexRoute
}

const FrontRouteRouteChildren: FrontRouteRouteChildren = {
  FrontChapterProjectRoute: FrontChapterProjectRoute,
  FrontChapterShowRoute: FrontChapterShowRoute,
  FrontChapterSystemRoute: FrontChapterSystemRoute,
  FrontLessonShowRoute: FrontLessonShowRoute,
  FrontTopicShowRoute: FrontTopicShowRoute,
  FrontVideoShowRoute: FrontVideoShowRoute,
  FrontLessonIndexRoute: FrontLessonIndexRoute,
  FrontSignIndexRoute: FrontSignIndexRoute,
  FrontSubscribeIndexRoute: FrontSubscribeIndexRoute,
  FrontTopicIndexRoute: FrontTopicIndexRoute,
  FrontVideoIndexRoute: FrontVideoIndexRoute,
}

const FrontRouteRouteWithChildren = FrontRouteRoute._addFileChildren(
  FrontRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/front': typeof FrontRouteRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/auth/forget': typeof AuthForgetRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/front/chapter/project': typeof FrontChapterProjectRoute
  '/front/chapter/show': typeof FrontChapterShowRoute
  '/front/chapter/system': typeof FrontChapterSystemRoute
  '/front/lesson/show': typeof FrontLessonShowRoute
  '/front/topic/show': typeof FrontTopicShowRoute
  '/front/video/show': typeof FrontVideoShowRoute
  '/front/lesson': typeof FrontLessonIndexRoute
  '/front/sign': typeof FrontSignIndexRoute
  '/front/subscribe': typeof FrontSubscribeIndexRoute
  '/front/topic': typeof FrontTopicIndexRoute
  '/front/video': typeof FrontVideoIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/front': typeof FrontRouteRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/auth/forget': typeof AuthForgetRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/front/chapter/project': typeof FrontChapterProjectRoute
  '/front/chapter/show': typeof FrontChapterShowRoute
  '/front/chapter/system': typeof FrontChapterSystemRoute
  '/front/lesson/show': typeof FrontLessonShowRoute
  '/front/topic/show': typeof FrontTopicShowRoute
  '/front/video/show': typeof FrontVideoShowRoute
  '/front/lesson': typeof FrontLessonIndexRoute
  '/front/sign': typeof FrontSignIndexRoute
  '/front/subscribe': typeof FrontSubscribeIndexRoute
  '/front/topic': typeof FrontTopicIndexRoute
  '/front/video': typeof FrontVideoIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/front': typeof FrontRouteRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/auth/forget': typeof AuthForgetRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/front/chapter/project': typeof FrontChapterProjectRoute
  '/front/chapter/show': typeof FrontChapterShowRoute
  '/front/chapter/system': typeof FrontChapterSystemRoute
  '/front/lesson/show': typeof FrontLessonShowRoute
  '/front/topic/show': typeof FrontTopicShowRoute
  '/front/video/show': typeof FrontVideoShowRoute
  '/front/lesson/': typeof FrontLessonIndexRoute
  '/front/sign/': typeof FrontSignIndexRoute
  '/front/subscribe/': typeof FrontSubscribeIndexRoute
  '/front/topic/': typeof FrontTopicIndexRoute
  '/front/video/': typeof FrontVideoIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/front'
    | '/about'
    | '/auth/forget'
    | '/auth/login'
    | '/auth/register'
    | '/front/chapter/project'
    | '/front/chapter/show'
    | '/front/chapter/system'
    | '/front/lesson/show'
    | '/front/topic/show'
    | '/front/video/show'
    | '/front/lesson'
    | '/front/sign'
    | '/front/subscribe'
    | '/front/topic'
    | '/front/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/front'
    | '/about'
    | '/auth/forget'
    | '/auth/login'
    | '/auth/register'
    | '/front/chapter/project'
    | '/front/chapter/show'
    | '/front/chapter/system'
    | '/front/lesson/show'
    | '/front/topic/show'
    | '/front/video/show'
    | '/front/lesson'
    | '/front/sign'
    | '/front/subscribe'
    | '/front/topic'
    | '/front/video'
  id:
    | '__root__'
    | '/'
    | '/front'
    | '/about'
    | '/auth/forget'
    | '/auth/login'
    | '/auth/register'
    | '/front/chapter/project'
    | '/front/chapter/show'
    | '/front/chapter/system'
    | '/front/lesson/show'
    | '/front/topic/show'
    | '/front/video/show'
    | '/front/lesson/'
    | '/front/sign/'
    | '/front/subscribe/'
    | '/front/topic/'
    | '/front/video/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  FrontRouteRoute: typeof FrontRouteRouteWithChildren
  AboutLazyRoute: typeof AboutLazyRoute
  AuthForgetRoute: typeof AuthForgetRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  FrontRouteRoute: FrontRouteRouteWithChildren,
  AboutLazyRoute: AboutLazyRoute,
  AuthForgetRoute: AuthForgetRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/front",
        "/about",
        "/auth/forget",
        "/auth/login",
        "/auth/register"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/front": {
      "filePath": "front/route.tsx",
      "children": [
        "/front/chapter/project",
        "/front/chapter/show",
        "/front/chapter/system",
        "/front/lesson/show",
        "/front/topic/show",
        "/front/video/show",
        "/front/lesson/",
        "/front/sign/",
        "/front/subscribe/",
        "/front/topic/",
        "/front/video/"
      ]
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/auth/forget": {
      "filePath": "auth/forget.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/front/chapter/project": {
      "filePath": "front/chapter/project.tsx",
      "parent": "/front"
    },
    "/front/chapter/show": {
      "filePath": "front/chapter/show.tsx",
      "parent": "/front"
    },
    "/front/chapter/system": {
      "filePath": "front/chapter/system.tsx",
      "parent": "/front"
    },
    "/front/lesson/show": {
      "filePath": "front/lesson/show.tsx",
      "parent": "/front"
    },
    "/front/topic/show": {
      "filePath": "front/topic/show.tsx",
      "parent": "/front"
    },
    "/front/video/show": {
      "filePath": "front/video/show.tsx",
      "parent": "/front"
    },
    "/front/lesson/": {
      "filePath": "front/lesson/index.tsx",
      "parent": "/front"
    },
    "/front/sign/": {
      "filePath": "front/sign/index.tsx",
      "parent": "/front"
    },
    "/front/subscribe/": {
      "filePath": "front/subscribe/index.tsx",
      "parent": "/front"
    },
    "/front/topic/": {
      "filePath": "front/topic/index.tsx",
      "parent": "/front"
    },
    "/front/video/": {
      "filePath": "front/video/index.tsx",
      "parent": "/front"
    }
  }
}
ROUTE_MANIFEST_END */
