// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/projects/:id": {
    params: {
      "id": string;
    };
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/contact" | "/projects" | "/projects/:id" | "/blog" | "/blog/:slug" | "/*";
  };
  "./layouts/home.tsx": {
    id: "layouts/home";
    page: "/";
  };
  "routes/home/index.tsx": {
    id: "routes/home/index";
    page: "/";
  };
  "./layouts/main.tsx": {
    id: "layouts/main";
    page: "/about" | "/contact" | "/projects" | "/projects/:id" | "/blog" | "/blog/:slug" | "/*";
  };
  "./routes/about/index.tsx": {
    id: "routes/about/index";
    page: "/about";
  };
  "./routes/contact/index.tsx": {
    id: "routes/contact/index";
    page: "/contact";
  };
  "./routes/projects/index.tsx": {
    id: "routes/projects/index";
    page: "/projects";
  };
  "./routes/projects/details.tsx": {
    id: "routes/projects/details";
    page: "/projects/:id";
  };
  "./routes/blog/index.tsx": {
    id: "routes/blog/index";
    page: "/blog";
  };
  "./routes/blog/details.tsx": {
    id: "routes/blog/details";
    page: "/blog/:slug";
  };
  "./routes/errors/not-found.tsx": {
    id: "routes/errors/not-found";
    page: "/*";
  };
};